### ISSUE TITLE
Wiederherstellen der zuletzt besuchten Seite nicht möglich

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/verona-modules-speedtest#1]
startPage in der playerConfig im `vopStartCommand` wird ignoriert.

**Comment by rhenck** [comment]
Der Player hat die aktuelle Seite in den Antwortdaten abgespeichert (lastSeenPageIndex). Mein Verständnis ist, dass das falsch ist. Stattdessen sollte er die "currentPage" im PlayerState setzen und dann "startPage" im Startkommando nutzen. Der Wert in den Antwortdaten kommt weg.

**Comment by paflov** [comment]
Ja, korrekt. Die aktuelle Seite wird ja an verschiedener Stelle ausgewertet und dist daher extra geführt und nicht teil des (theoretisch offenene) Antwortdatenformats.

**Comment by rhenck** [comment]
Intervention von Martin: Der Speedtest-Player soll nach außen so tun, als hätte er keine Seiten. Er hat nur sowas wie einen internen Zustand, den er selbstständig wiederherstellt. Der Host soll nicht davon erfahren, dass es in der Unit mehrere Seiten gibt, damit keine ellenlange Navigationsleiste gezeigt wird. Ich werde konsequenterweise alles was über die API Dinge kommuniziert, die nach Seiten aussehen zurückbauen.

**Comment by paflov** [comment]
ooooookay
